name: Search and Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests beautifulsoup4
    - name: Setup ChromeDriver
      uses: browser-actions/setup-chromedriver@v1
    - name: Verify ChromeDriver
      run: chromedriver --version
    - name: Run Python script
      run: python script.py
      env:
        SEARCH_KEYWORD: "python"  # 设置您的关键字
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ji.txt
        path: data/ji.txt
