name: Parse Channels, Split & Base64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ignore_userinfo:
        description: 'Ignore userinfo for deduplication'
        default: 'true'
        required: false
  schedule:
    - cron: '0 */12 * * *' # 每 12 小时运行

jobs:
  run_python_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create timestamped directory
      run: |
        mkdir -p ./archives/$(date +'%Y%m')
        mkdir -p ./archives/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')
        mkdir -p ./archives/channels/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')
        # 复制文件到归档目录
        [ -f split/mixed ] && cp split/mixed ./archives/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')/ || echo "split/mixed not found."
        [ -f telegramchannels.json ] && cp telegramchannels.json ./archives/channels/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')/ || echo "telegramchannels.json not found."
        [ -f configtg.txt ] && cp configtg.txt ./archives/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')/ || echo "configtg.txt not found."
        [ -f configtg.yaml ] && cp configtg.yaml ./archives/$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')/ || echo "configtg.yaml not found."

    - name: Grab content and update backup
      run: |
        mkdir -p archives/latest_backup
        curl https://github.com/qjlxg/hy2/raw/main/configtg.txt -o archives/latest_backup/mixed || echo "Failed to download configtg.txt backup."

    - name: Commit and push archived backups
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'Action@github.com'
        git add archives/
        git commit -m "Archived backups" || echo "No changes to archive."
        git push || echo "Failed to push archive changes."

    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.x'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ steps.setup-python.outputs.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyyaml

    - name: Run TG Parser
      env:
        THRD_PARS: '128'
        PARS_DP: '3'
        USE_INV_TC: 'n'
        IGNORE_USERINFO: ${{ github.event.inputs.ignore_userinfo || 'true' }}
        LOG_LEVEL: 'info'
      run: python3 tg-parser.py | tee parser_output.log

    - name: Verify deduplication in configtg.txt
      run: |
        if [ -f configtg.txt ]; then
          total=$(wc -l < configtg.txt)
          unique=$(sort configtg.txt | uniq | wc -l)
          duplicates=$((total - unique))
          echo "Total links: $total, Unique links: $unique, Duplicates: $duplicates, Duplicate rate: $(echo "scale=2; $duplicates/$total*100" | bc)%"
          if [ $duplicates -gt 0 ]; then
            echo "Warning: Found $duplicates duplicate links in configtg.txt"
            sort configtg.txt | uniq -d > duplicates.txt
          fi
        else
          echo "failed: configtg.txt not found."
            exit 1
        fi

    - name: Upload parser logs and duplicates
      if: actions/upload-artifact@v4
      with:
        name: parser-logs
        path: |
          parser_output.log
          duplicates.txt
        overwrite: true
        retention-days: 7

    - name: Commit and push parser updated files
      run: actions
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add configtg.txt configtg.yaml telegramchannels.json invalidtelegramchannels.json
        git diff --staged --quiet || git commit -m "Update TG configs and channel lists" || echo "No changes from parser."
        git push || echo "Failed to push parser changes."

    - name: Split UTF-8 and update subscriptions
      run: |
        [ -f python/splitter.py ] && python python/splitter.py || echo "python/splitter.py not found, skipping split."

    - name: Verify deduplication in split files
      run: |
        for file in python/*; do
          if [ -f "$file" ]; then
            total=$(wc -l < "$file")
            unique=$(sort "$file" | uniq | wc -l)
            duplicates=$((total - unique))
            echo "$file: Total links: $total, Unique links: $unique, Duplicates: $duplicates, Duplicate rate: $(echo "scale=2; $duplicates/$total*100" | bc)%"
            if [ $duplicates -gt 0 ]; then
              echo "Warning: Found $duplicates duplicate links in $file"
              sort "$file" | uniq -d >> split_duplicates.txt
            fi
          fi
        done

    - name: Upload split duplicates
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: split-duplicates
        path: split_duplicates.txt
        overwrite: true
        retention-days: 7

    - name: Check for split changes
      id: changes_split
      run: |
        git diff --quiet python/vmess python/vless python/trojan python/ss python/socks python/hysteria2 python/tuic python/hysteria python/naive python/ssr python/unknown || echo "::set-output name=changed::true"

    - name: Commit and push split files
      if: steps.changes_split.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add python/vmess python/vless python/trojan python/ss python/socks python/hysteria2 python/tuic python/hysteria python/naive python/ssr python/unknown
        git commit -am "Update v2ray subscriptions"
        git push || echo "Failed to push split files."

    - name: Create split directory
      run: mkdir -p split

    - name: Convert mixed to base64
      run: |
        [ -f configtg.txt ] && cat configtg.txt | base64 | tr -d '\n' > split/mixed || echo "configtg.txt not found."

    - name: Convert socks to base64
      run: |
        [ -f python/socks ] && cat python/socks | base64 | tr -d '\n' > split/socks || echo "python/socks not found."

    - name: Convert ss to base64
      run: |
        [ -f python/ss ] && cat python/ss | base64 | tr -d '\n' > split/ss || echo "python/ss not found."

    - name: Convert trojan to base64
      run: |
        [ -f python/trojan ] && cat python/trojan | base64 | tr -d '\n' > split/trojan || echo "python/trojan not found."

    - name: Convert vless to base64
      run: |
        [ -f python/vless ] && cat python/vless | base64 | tr -d '\n' > split/vless || echo "python/vless not found."

    - name: Convert vmess to base64
      run: |
        [ -f python/vmess ] && cat python/vmess | base64 | tr -d '\n' > split/vmess || echo "python/vmess not found."

    - name: Convert tuic to base64
      run: |
        [ -f python/tuic ] && cat python/tuic | base64 | tr -d '\n' > split/tuic || echo "python/tuic not found."

    - name: Convert hysteria2 to base64
      run: |
        [ -f python/hysteria2 ] && cat python/hysteria2 | base64 | tr -d '\n' > split/hysteria2 || echo "python/hysteria2 not found."

    - name: Convert hysteria to base64
      run: |
        [ -f python/hysteria ] && cat python/hysteria | base64 | tr -d '\n' > split/hysteria || echo "python/hysteria not found."

    - name: Convert naive to base64
      run: |
        [ -f python/naive ] && cat python/naive | base64 | tr -d '\n' > split/naive || echo "python/naive not found."

    - name: Convert ssr to base64
      run: |
        [ -f python/ssr ] && cat python/ssr | base64 | tr -d '\n' > split/ssr || echo "python/ssr not found."

    - name: Check for base64 changes
      id: changes64
      run: |
        git diff --quiet split/mixed split/socks split/ss split/trojan split/vless split/vmess split/tuic split/hysteria2 split/hysteria split/naive split/ssr || echo "::set-output name=changed::true"

    - name: Commit and push base64 files
      if: steps.changes64.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add split/
        git commit --allow-empty -am "Update Base64 output files"
        git push || echo "Failed to push Base64 changes."
