name: Parse Channels, Split & Base64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: "0 4,12,18 * * *"
jobs:
  run_python_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    - name: Create timestamped directory and archive
      run: |
        TIMESTAMP_DIR="$(date +'%Y%m')/$(date +'%Y-%m-%d_%H-%M-%S')"
        mkdir -p "./archives/${TIMESTAMP_DIR}"
        mkdir -p "./archives/channels/${TIMESTAMP_DIR}"
        # 复制文件到归档目录，如果文件不存在则输出警告
        cp splitted/mixed "./archives/${TIMESTAMP_DIR}/" || echo "Warning: splitted/mixed not found, skipping archive."
        cp telegramchannels.json "./archives/channels/${TIMESTAMP_DIR}/" || echo "Warning: telegramchannels.json not found, skipping archive."
        cp configtg.txt "./archives/${TIMESTAMP_DIR}/" || echo "Warning: configtg.txt not found, skipping archive."
        cp configtg.yaml "./archives/${TIMESTAMP_DIR}/" || echo "Warning: configtg.yaml not found, skipping archive."

    - name: Grab content and update backup
      run: |
        curl https://github.com/qjlxg/hy2/raw/main/configtg.txt -o archives/latest_backup/mixed || { echo "Error: Failed to download configtg.txt backup. Exiting."; exit 1; }

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'Action@github.com'
        git add .
        git commit -m "Archived backups"
        git push
    
    
    - name: Set up Parser
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install Parser dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run Parser
      env:
          THRD_PARS: '128'
          PARS_DP: '1'
          USE_INV_TC: 'n'
      run: |
        python tg-parser.py
          
    - name: Local Authentication
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Commit & push Parser
      run: |
        git add .
        git commit -m "Update files"
        git pull
        git push

    - name: Set up Splitter
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

  
    - name: Split UTF-8 and update subscriptions
      run: |
        python python/splitter.py

    - name: Check for split changes
      id: changes
      run: |
        git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'

    - name: Commit and push splitted
      if: steps.changes.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add python/vmess python/vless python/trojan python/ss python/socks python/hysteria2 python/hy2 python/tuic
          git commit -am "Update v2ray subscriptions"
          git push

    - name: Convert mixed to base64
      run: |
          content=$(cat configtg.txt | base64| tr -d '\n')
            echo "$content" > splitted/mixed

    - name: Convert socks to base64
      run: |
          content=$(cat python/socks | base64| tr -d '\n')
            echo "$content" > splitted/socks

    - name: Convert ss to base64
      run: |
          content=$(cat python/ss | base64| tr -d '\n')
            echo "$content" > splitted/ss

    - name: Convert trojan to base64
      run: |
          content=$(cat python/trojan | base64| tr -d '\n')
            echo "$content" > splitted/trojan

    - name: Convert vless to base64
      run: |
          content=$(cat python/vless | base64| tr -d '\n')
            echo "$content" > splitted/vless

    - name: Convert vmess to base64
      run: |
          content=$(cat python/vmess | base64| tr -d '\n')
            echo "$content" > splitted/vmess

    - name: Convert tuic to base64
      run: |
          content=$(cat python/tuic | base64| tr -d '\n')
            echo "$content" > splitted/tuic

    - name: Convert hysteria2 to base64
      run: |
          content=$(cat python/hysteria2 | base64| tr -d '\n')
            echo "$content" > splitted/hysteria2

    - name: Convert hy2 to base64
      run: |
          content=$(cat python/hy2 | base64| tr -d '\n')
            echo "$content" > splitted/hy2
       
    - name: Check for Base64 Changes
      id: changes64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push Base64
      if: steps.changes.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add splitted/mixed
          git add splitted/*
          git commit --allow-empty -m "Update output files"
          git push
