name: Run TG Parser and Update Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每天运行，例如 UTC 时间凌晨 0 点
    - cron: '0 0 * * *'

jobs:
  run_parser_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 假设 requirements.txt 中包含了 tg-parser.py 所需的所有库
        pip install -r requirements.txt

    - name: Run TG Parser
      env:
        # 设置环境变量，与你的脚本中的 os.getenv 对应
        THRD_PARS: '128' # 并发抓取线程数
        PARS_DP: '1'     # 每个频道抓取页面深度
        USE_INV_TC: 'n'  # 是否使用无效频道列表
      run: |
        # 运行你的 Python 脚本
        python tg-parser.py

    - name: Configure Git
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Commit and push updated files
      run: |
        # 添加所有可能被脚本修改的文件
        git add configtg.txt telegramchannels.json invalidtelegramchannels.json
        # 检查是否有实际更改，避免空提交
        git diff --staged --quiet || git commit -m "Update TG configs and channel lists"
        # 推送更改到仓库
        git push

